//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HicknHack.Twofold.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HicknHack.Twofold.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///
        ///namespace Example
        ///{
        ///    public partial class ExampleRenderer
        ///    {
        ///
        ///		public static void ShowMethod(MethodDescriptor method)
        ///		{
        ///													|#{method.ReturnType} #{method.Name}(#{ShowArguments(method.Arguments)}) {
        ///													|    #{method.Body}
        ///													|}
        ///		}
        ///
        ///		public static void ShowArguments(List&lt;ArgumentDescriptor&gt; arguments)
        ///		{
        ///			bool first = true;
        ///			foreach(var argument in arguments) {
        ///				if(first == false) {
        ///													\#{&quot;, &quot;}
        ///				}
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Include {
            get {
                return ResourceManager.GetString("Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma include &quot;Include&quot;
        ///
        ///using System;
        ///
        ///namespace Example
        ///{
        ///    public partial class ExampleRenderer
        ///    {
        ///        public static void TwofoldMain(ClassDescriptor classDescriptor)
        ///        {
        ///													|using System;
        ///													|
        ///													|namespace Generated
        ///													|{
        ///													|    class #{classDescriptor.Name}
        ///													|    {
        ///			foreach(var method in classDescriptor.Methods) {
        ///													=        ShowMethod(method);
        ///			}
        ///													|    }
        ///													|}
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Diagnostics;
        ///
        ///namespace Example
        ///{
        ///    public partial class ExampleRenderer
        ///    {
        ///		public static void Helper(string text, int level)
        ///		{			
        ///			=  Helper2(text, level);
        ///		}
        ///
        ///		public static void Helper2(string text, int level)
        ///		{
        ///			\#{text}
        ///			PrintRecursive(text, level - 1);
        ///		}
        ///
        ///		public static void PrintRecursive(string text, int level)
        ///		{
        ///			if(level &gt; 0) {
        ///				=    Helper(text, level);
        ///			}
        ///		}
        ///
        ///        public static void TwofoldMain(string text, int level)
        ///        {
        ///			Pri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Recursion {
            get {
                return ResourceManager.GetString("Recursion", resourceCulture);
            }
        }
    }
}
