//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Example.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Example
        ///{
        ///	public static class Helper
        ///	{
        ///		public static int Answer()
        ///		{
        ///			int i = 42;
        ///			return i;
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string ExampleInclude {
            get {
                return ResourceManager.GetString("ExampleInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma include &quot;ExampleInclude&quot;
        ///
        ///using System;
        ///
        ///namespace Example
        ///{
        ///    public class ExampleRenderer
        ///    {
        ///        public static void TwofoldMain(string text)
        ///        {
        ///            System.Console.WriteLine(&quot;The answer is: {0} {1}&quot;, Helper.Answer(), text);
        ///            for (int i = 0; i &lt; 10; ++i) {
        ///																							| Item #{i.ToString()} in the list.
        ///			}
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string ExampleMain {
            get {
                return ResourceManager.GetString("ExampleMain", resourceCulture);
            }
        }
    }
}
